src/main/app/src/apiUtils/index.js
src/main/app/src/components/CheckboxGroup/index.jsx
src/main/app/src/components/CreateToteutusPage/CreateToteutusForm.jsx
src/main/app/src/components/CreateToteutusPage/index.jsx
src/main/app/src/components/ToteutusForm/JarjestamisPaikatSelect.jsx
src/main/app/src/components/ToteutusForm/PohjaSection.jsx
src/main/app/src/components/ToteutusForm/ToteutusForm.jsx
src/main/app/src/components/ToteutusForm/index.jsx
src/main/app/src/state/createToteutusForm/actions.js
src/main/app/src/state/createToteutusForm/index.js
src/main/app/src/state/createToteutusForm/utils.js

Toteutuksen voi luoda aimmen luodun toteutuksen pohjalta valitsemalla "Pohjan valinta" => "Kopio pohjaksi aiemmin luotu toteutus". [Linkki testaamiseen](https://virkailija.hahtuvaopintopolku.fi/kouta/organisaatio/1.2.246.562.10.594252633210/koulutus/1.2.246.562.13.00000000000000000001/toteutus).
Huomioitavaa:
- Valintaperusteet eivät tällä hetkellä kopioidu, koska valitussa toteutuksessa voi olla eri koulutus, kuin luotavassa toteutuksessa

KTO-104 toteutuksen kopiointi

---

src/main/app/package-lock.json
src/main/app/package.json
src/main/app/src/components/CreateKoulutusPage/CreateKoulutusForm.jsx
src/main/app/src/components/FormCollapse/ClearFormSection.jsx
src/main/app/src/components/FormCollapse/index.jsx
src/main/app/src/components/FormCollapseGroup/index.jsx
src/main/app/src/components/KoulutusForm/KoulutusForm.jsx
src/main/app/src/components/KoulutusForm/ToteutuksetModal.jsx
src/main/app/src/components/KoulutusForm/ToteutuksetSection.jsx
src/main/app/src/components/Modal/index.jsx
src/main/app/src/components/useApiAsync/index.js
src/main/app/src/state/createKoulutusForm/actions.js
src/main/resources/kouta-ui-oph.properties

[Linkki testaamiseen](https://virkailija.hahtuvaopintopolku.fi/kouta/organisaatio/1.2.246.562.10.594252633210/koulutus) **(hahtuva)**.
"Koulutuksee liitetyt toteutukset"-osiossa käyttäjä voi valita "Liitä toteututus", josta joko valitsemalla "Luo uusi toteututus", tai "Kopioi pohjaksi aiemmin luotu toteututs", pääsee käyttäjä joku luomaan koulutukselle uutta toteutusta, tai luomaan koulutukselle toteutusta käyttäen pohjana valittua toteutusta.

KTO-105 Toteutuksen liittäminen koulutukseen

---

src/main/app/src/apiUtils/index.js
src/main/app/src/components/CreateHakukohdePage/CreateHakukohdeFooter.jsx
src/main/app/src/components/EditHakukohdePage/EditHakukohdeFooter.jsx
src/main/app/src/components/EditHakukohdePage/EditHakukohdeForm.jsx
src/main/app/src/components/EditHakukohdePage/EditHakukohdeHeader.jsx
src/main/app/src/components/EditHakukohdePage/EditHakukohdeSteps.jsx
src/main/app/src/components/EditHakukohdePage/index.jsx
src/main/app/src/components/EditKoulutusPage/EditKoulutusHeader.jsx
src/main/app/src/components/EditToteutusPage/EditToteutusHeader.jsx
src/main/app/src/components/FormEditInfo/FormEditInfo.stories.jsx
src/main/app/src/components/FormEditInfo/index.jsx
src/main/app/src/components/HakukohdeForm/LiitteetSection.jsx
src/main/app/src/components/HomePage/ListTable.jsx
src/main/app/src/components/MainPage/index.jsx
src/main/app/src/state/createHakukohdeForm/actions.js
src/main/app/src/state/createHakukohdeForm/utils.js
src/main/app/src/state/editHakukohdeForm/actions.js
src/main/app/src/state/editHakukohdeForm/index.js
src/main/app/src/utils.js
src/main/java/fi/oph/kouta/UrlConfiguration.java
src/main/resources/kouta-ui-oph.properties

[Linkki testaamiseen](https://virkailija.untuvaopintopolku.fi/kouta/hakukohde/1.2.246.562.20.00000000000000000004/muokkaus) (untuva)

KTO-113 hakukohteen muokkaus

---

src/main/app/src/components/CreateToteutusPage/index.jsx
src/main/app/src/components/Dropdown/index.jsx
src/main/app/src/components/DropdownIcon/DropdownIcon.stories.jsx
src/main/app/src/components/DropdownIcon/index.jsx
src/main/app/src/components/EditToteutusPage/index.jsx
src/main/app/src/components/HomePage/KoulutuksetSection.jsx
src/main/app/src/components/KoodistoversiotContext/index.jsx
src/main/app/src/components/KoulutusForm/BaseSelectionSection.jsx
src/main/app/src/components/Label/index.jsx
src/main/app/src/components/Radio/Radio.stories.jsx
src/main/app/src/components/Radio/index.jsx
src/main/app/src/components/Select/index.jsx
src/main/app/src/components/ToteutusForm/AlkamiskausiFields.jsx
src/main/app/src/components/ToteutusForm/JarjestamisPaikatSelect.jsx
src/main/app/src/components/ToteutusForm/JarjestamisTiedotSection.jsx
src/main/app/src/components/ToteutusForm/KorkeakouluOsaamisalatSection.jsx
src/main/app/src/components/ToteutusForm/KorkeakoulutuOsaamisalatFields.jsx
src/main/app/src/components/ToteutusForm/KuvausSection.jsx
src/main/app/src/components/ToteutusForm/OpetusaikaRadioGroup.jsx
src/main/app/src/components/ToteutusForm/OpetuskieliCheckboxGroup.jsx
src/main/app/src/components/ToteutusForm/OpetustapaCheckboxGroup.jsx
src/main/app/src/components/ToteutusForm/OsiotSelect.jsx
src/main/app/src/components/ToteutusForm/PohjaSection.jsx
src/main/app/src/components/ToteutusForm/ToteutusForm.jsx
src/main/app/src/components/ToteutusForm/ToteutusForm.stories.jsx
src/main/app/src/components/YearSelect/index.jsx
src/main/app/src/components/useKoodisto/index.js
src/main/app/src/components/useKoodistoOptions/index.js
src/main/app/src/state/createToteutusForm/utils.js
src/main/app/src/utils.js

[Linkki testaamiseen](https://virkailija.hahtuvaopintopolku.fi/kouta/organisaatio/1.2.246.562.10.594252633210/koulutus/1.2.246.562.13.00000000000000000054/toteutus)
Toteutuslomake korkeakoulutukselle. Pohjautuu [tähän](https://app.zeplin.io/project/5b921d8069630348ec23f8d6/screen/5bec12cfaf23577ecbfcd48e) leiskaan.

KTO-121 Korkeakoulutuksen toteutuslomake

---

src/main/app/cypress/integration/toteutusForm/snapshots.js
src/main/app/cypress/integration/valintaperusteForm/createValintaperusteForm.js
src/main/app/cypress/integration/valintaperusteForm/snapshots.js
src/main/app/src/components/CreateValintaperustePage/CreateValintaperusteForm.jsx
src/main/app/src/components/EditValintaperustePage/EditValintaperusteForm.jsx
src/main/app/src/utils/getValintaperusteFormConfig.js

- muutettu myös ValintaperusteFormConfig käyttämään registerField-syntaksia (voi määrittää kenttien näkyvyyden per koulutustyyppi).
- poistettu valintatapa-osion näkyvyys tietyiltä koulutustyypeiltä.

KTO-345  valintatavattomat koulutustyypit

---

src/main/app/src/components/HakuForm/HakukohteetSection.jsx
src/main/app/src/components/HomePage/ListTable.jsx
src/main/app/src/components/KoulutusForm/ToteutuksetSection.jsx
src/main/app/src/components/RelatedEntitiesTable.jsx
src/main/app/src/components/ToteutusForm/HakukohteetSection.jsx
src/main/app/src/translations/fi.js

- Refaktorointia: Käytetään samaa komponenttia haun hakukohteiden, toteutuksen hakukohteiden ja koulutuksen toteutusten esittämiseen.
- Esitetään edellä mainitut ListTable-komponentin avulla.
- Pieniä parannuksia ListTable-komponenttiin

KTO-502: Haun muokkauksessa hakukohteet eivät ole allekkain listattuna

---

src/main/app/src/apiUrls/index.js
src/main/app/src/index.js

- This will add Caller-Id header to the request

KTO-693: Use httpClient to request frontProperties

---

src/main/app/src/apiUtils/index.js
src/main/app/src/components/KoulutusForm/KuvausSection/TekstiKuvausSection.jsx
src/main/app/src/components/StyledSectionHTML.jsx
src/main/app/src/components/ToteutusForm/OsaamisalatSection.jsx
src/main/app/src/constants.js
src/main/app/src/index.js
src/main/app/src/localisation.js
src/main/app/src/theme/index.js
src/main/app/src/translations/en.js
src/main/app/src/translations/fi.js
src/main/app/src/translations/index.js
src/main/app/src/translations/sv.js
src/main/app/src/utils/ePeruste/getEPerusteKuvaus.js
src/main/app/src/utils/index.js

- KOMO ePerusteen kuvauksen noutaminen oikeista kentistä (KTO-688)
- KOMO ePerusteen kuvauksen muotoilujen esittäminen. (KTO-604)

KTO-604 & KTO-688: KOMO ePeruste kuvaus parannuksia

---

src/main/app/src/components/FormSteps/index.jsx
src/main/app/src/components/HomePage/HakukohteetSection/index.jsx
src/main/app/src/components/HomePage/HautSection.jsx
src/main/app/src/components/HomePage/KoulutuksetSection.jsx
src/main/app/src/components/HomePage/ToteutuksetSection/index.jsx
src/main/app/src/components/HomePage/ValintaperusteetSection.jsx
src/main/app/src/components/OppilaitosFormSteps/index.jsx
src/main/app/src/constants.js

- Put icon names to constants instaed of hardcoding them to components

KTO-428: Update entity icons

---

src/main/app/src/utils/createErrorBuilder.js
src/main/app/src/utils/formConfigUtils.js
src/main/app/src/utils/getValintaperusteFormConfig.js

- Pääasiassa uuden 'kokeet tai lisänäytöt'-osion validointien korjaukset sekä valintaperusteelle, että hakukohteelle.

KTO-731: Valintaperusteiden validointien korjaukset

---

.gitignore
README.md
src/main/app/.env
src/main/app/src/setupProxy.js
src/main/app/src/urls.ts

- Parannettu lokaalin kehitysproxyn konffia siten, että sitä voi paremmin käyttää kouta-backendin kanssa
- Parannettu dokumentaatiota liittyen ajamiseen lokaalisti kouta-backendin kanssa

KTO-948: Kouta-ui ja kouta-backend ajaminen yhdessä

---

src/main/app/src/components/PohjaValintaSection.tsx
src/main/app/src/hooks/useSoraKuvausOptions/index.tsx
src/main/app/src/pages/HomePage/HakukohteetSection/LiitoksetModal.tsx
src/main/app/src/pages/HomePage/ToteutuksetSection/KoulutusModal.tsx
src/main/app/src/pages/haku/HakuForm/HakukohteetModal.tsx
src/main/app/src/pages/hakukohde/HakukohdeForm/KuvausSection.tsx
src/main/app/src/pages/toteutus/ToteutusForm/HakukohteetModal.tsx

Bäkkärin /list loppuisista apeista tulevaa dataa näytetään käyttöliittymässä dropdowneissa. Lisätty näihin dropdowneihin entiteetin tila suluissa jotta käyttäjän helpompi löytää haluamansa.

Kto 505 tila näkyviin dropdowneihin

---

src/main/app/.gitignore
src/main/app/cypress/integration/__snapshots__/toteutus.test.ts.snap
src/main/app/cypress/integration/toteutusForm/createToteutusForm.ts
src/main/app/package-lock.json
src/main/app/package.json
src/main/app/src/constants.ts
src/main/app/src/contexts/FormNameContext.ts
src/main/app/src/hooks/form.ts
src/main/app/src/pages/toteutus/ToteutusForm/JarjestamisTiedotSection/index.tsx
src/main/app/src/utils/toteutus/__snapshots__/getToteutusByFormValues.test.ts.snap
src/main/app/src/utils/toteutus/getToteutusByFormValues.test.ts
src/main/app/src/utils/toteutus/getToteutusByFormValues.ts
src/main/app/src/utils/toteutus/toteutusVisibilities.test.ts
src/main/app/src/utils/toteutus/toteutusVisibilities.ts

Apurahaosio (stipendi) näkyviin vain AMK + YO -koulutustyypeille JOS valituissa opetuskielissä on englanti

KTO-891: conditional toteutus Stipendi fields

---

src/main/app/src/utils/koulutus/__snapshots__/getFormValuesByKoulutus.test.ts.snap
src/main/app/src/utils/koulutus/getFormValuesByKoulutus.ts

koulutusKoodiUrin default arvoksi undefined, tyhjä string aiheuttaa validointivirheen bäkkärissä tutkinnon osille

KTO-283-korjaus

---

src/main/app/src/utils/toteutus/getToteutusFormConfig.ts

- Disallow zero
- Validate on any 'tila'
- Show better validation error message

KTO-1168: Improve KOMOTO maksunMaara validation

---

src/main/app/src/components/LomakeFields/index.tsx

This reverts commit 4c149544a6d2183948bbe3d1ce9175bf47a91843.

Revert "Comment out haun asetukset button in LomakeFields."

---

src/main/app/src/components/ListTable.tsx
src/main/app/src/pages/HomePage/Filters.tsx
src/main/app/src/pages/HomePage/HakukohteetSection/index.tsx
src/main/app/src/pages/HomePage/useFilterState.ts
src/main/app/src/pages/HomePage/utils.ts
src/main/app/src/pages/toteutus/ToteutusForm/HakukohteetSection.tsx
src/main/app/src/utils/api/getSearchQueryParams.ts

Etusivun ja toteutuksen hakukohdelistauksiin haku-sarake ja vapaasanahaku.

OY-3663 & OY-3857

---

src/main/app/src/pages/koulutus/KoulutusForm/TutkinnonOsaKoulutusNimiSection.tsx
src/main/app/src/pages/toteutus/ToteutusForm/TiedotSection.tsx
src/main/app/src/pages/toteutus/ToteutusForm/ToteutusForm.tsx

https://jira.eduuni.fi/browse/OY-4063

OY-4063: Enable renaming koulutus and toteutus for tutkinnonosa-ala

---

src/main/app/src/pages/HomePage/OrganisaatioDrawer/useReadableOrganisaatioHierarkia.ts
src/main/app/src/utils/organisaatio/hierarkiaHelpers.test.ts
src/main/app/src/utils/organisaatio/hierarkiaHelpers.ts

https://jira.eduuni.fi/browse/OPHJOD-50
Vaatii toimiakseen kunnolla myös https://jira.eduuni.fi/browse/OPHJOD-50

Flatten the whole hierarchy utilizing filter and remove lodash

---

src/main/app/src/pages/HomePage/HakukohteetSection/index.tsx
src/main/app/src/pages/HomePage/StateChangeConfirmationModal.tsx
src/main/app/src/pages/HomePage/StateChangeResultModal.tsx
src/main/app/src/pages/HomePage/ToteutuksetSection/changeToteutuksetState.ts
src/main/app/src/pages/HomePage/ToteutuksetSection/index.tsx
src/main/app/src/translations/fi.json
src/main/app/src/urls.ts
src/main/java/fi/oph/kouta/UrlConfiguration.java
src/main/resources/kouta-ui-oph.properties

https://jira.eduuni.fi/browse/OY-4120

OY-4120 mass update toteutus tila

---

src/main/app/src/pages/koulutus/KoulutusForm/tarjoajat/TarjoajatSection.tsx
src/main/app/src/translations/fi.json
src/main/app/src/utils/koulutus/koulutusRemoteErrorsToFormErrors.ts

… pakko antaa väh. yksi tarjoaja jos koulutus julkaistu ja ei-julkinen.

OPHJOD-66: Tiukennettu tarjoaja-validointia korkeakoulusidonnaisille koulutuksille

---

src/main/app/src/utils/index.test.ts
src/main/app/src/utils/index.ts

https://jira.eduuni.fi/browse/OY-4505

Add maybeParseNumber to handle comma

---

src/main/app/package-lock.json
src/main/app/package.json

form-data-kirjastossa olleen tietoturvahaavoittuvuuden takia

OY-5264: Päivitetty Axios uusimpaan versioon
